dist: trusty
sudo: false
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            # install clang and ninja
            - clang++
            - ninja-build
            
script:
    - cmake -G Ninja .
    - ninja
    - ctest
