dist: trusty
sudo: false
language: cpp

# addons:
    # apt:
        # sources:
            # - ubuntu-toolchain-r-test
        # packages:
            # install clang and ninja
            #- ninja-build
            #- clang
            
script:
    - cmake .
    - make
    - cd test
    # - ctest
    # - ./gtest_ex
